apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:latest
    ports:
    - containerPort: 80
    env:
    - name: env
      value: prod
