apiVersion: v1
kind: Pod
metadata:
  name: hostpath-mount
spec: 
  volumes: 
  - name: hostpath-vol
    hostPath:
       path: /home/ubuntu/pod_data
       type: DirectoryOrCreate       
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
    