apiVersion: v1
kind: Pod
metadata: 
  name: init-container
spec:
  initContainers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"] 
    args: ["-c", "sleep10"] 
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80  