apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: itd-k8s
  source:
    repoURL: https://github.com/kesarkar-M/DevOps.git
    targetRevision: main
    path: K8s/argocd/kube_configs
  destination:
    server: https://13.127.77.61:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

