apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
  spec:
    template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
        - /bin/sh
        - -c
        - "sleep 10"
      restartPolicy: Never
      backoffLimit: 10
      parallelism: 4
      completions: 2
      activeDeadlineSeconds: 5