apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-example
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "20"]
      restartPolicy: Never
  