apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-example
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
        - /bin/sh
        - -c
        - "sleep 10; exit 1"
      restartPolicy: Never
  backoffLimit: 10
  parallelism: 4